### ISSUE TITLE
Consistently return tbl_lazy obejct from functions

### ISSUE THREAD

**Issue by dietrichson** [chi2labs/moodleR#11]
As per comment made in #9 by @alex-ondrus

**Comment by dietrichson** [comment]
@alex-ondrus I have updated some of the heavier queries to return a reference rather than the full download. I have left the smaller ones (e.g. config) with collect, as they are never going to be big enough to clog down your system. The update has been made in feature branch #issue_10. If this seems reasonable to you, please let me know, and I´ll incorporate these changes into the main branch and push new version to CRAN.

**Comment by alex-ondrus** [comment]
I think that's a good approach. The only inconsistency is that `mdl_courses` does not include `collect` while `mdl_users` does include `collect`. My user table is about 5 times as large as my courses table, which makes me think it should be the other way around (or just include `collect` for both). Is the course table usually larger than the user table?

**Comment by dietrichson** [comment]
I agree. I will fix the inconsistency and merge the changes
