### ISSUE TITLE
Download course content 

### ISSUE THREAD

**Issue by aarathybabu97** [chi2labs/moodleR#5]
Hello, 

I am working on a research project which requires me to interact with moodle via R and I had a few questions regarding the functions of the package. Is there an option/way to access the course content through the package?  Also, is it possible for a Moodle that is not local to the system to interact with this package via MoodleAPI? 

Any information regarding the same is much appreciated as there is limited support on several platforms regarding this. 

Regards, 
Aarathy

**Comment by dietrichson** [comment]
Some of the course content (courseware) is stored outside the database, and
so is not accessible through the connection.

We don't have an API connector, but we're happy to work with you to add
this functionality.
