### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by Testoreno** [chi2labs/moodleR#7]
Hello,
I´m currently working on a project where I have to connect a RStudio-server with a Moodle-database. I have created the config.yml with the database information but MoodleR seems to ignore the port-specification in the config file so the connection fails (our database admin told me, that MoodleR tries to connect via standard 3306 instead of the specified port 3308).
Is there any other way to force MoodleR to use the correct port?
Thank you in advance!

My config.yml looks like this:
default:
  moodleR:
    user: "XXX"
    password: "XXX"
    dbname: "XXX"
    host: "XXX"
    port: 3308

**Comment by dietrichson** [comment]
@Testoreno yes. It is indeed ignored. I will update and you should be able to connect with the dev-version.

**Comment by dietrichson** [comment]
@Testoreno can you try updating the package with:
`devtools::install_github("chi2labs/moodleR", ref="issue_7")`
and let me know how it goes?

**Comment by Testoreno** [comment]
Thank you for your quick response. Unfortunately I still get the same error:
Error: Failed to connect: Can't connect to MySQL server on 'XXX:3306' (111)
(The ":3306" is added by moodleR and is not part of the server name in config.yml)

**Comment by dietrichson** [comment]
OK. I'll have another go today.

**Comment by dietrichson** [comment]
@Testoreno I have tried making an update to the code in the branch issue_7, however, the MariaDB driver seems to ignore the port specification. I tried this:

> DBI::dbConnect(
>     RMariaDB::MariaDB(),
>     user = myConf$moodleR$user,
>     password = myConf$moodleR$password,
>     dbname = myConf$moodleR$dbname,
>     host = myConf$moodleR$host,
>     port = 3308,
>     bigint = "integer64"
>   ) -> my_connection

And it connected beutifully... to my moddle-instance listening on port 3306.

**Comment by dietrichson** [comment]
@Testoreno if you are running mysql locally this may be the issue as well:

https://stackoverflow.com/questions/50160128/why-wont-mysql-client-use-the-port-i-specify/50160284

As far as I can tell, this is what I am experiencing.

**Comment by Testoreno** [comment]
@dietrichson Thank you. I'll forward the information to my Moodle-admins. Maybe it helps them.

**Comment by Testoreno** [comment]
> @Testoreno if you are running mysql locally this may be the issue as well:
> 
> https://stackoverflow.com/questions/50160128/why-wont-mysql-client-use-the-port-i-specify/50160284
> 
> As far as I can tell, this is what I am experiencing.

My Moodle-admins tried to connect manually to the mysql database and didn't experience the described issue.
Do you have any other idea how to solve the problem or is a direct connection to mysql the only solution?
